### PR TITLE
Android: isInstalled fails for package entries with double quotes

### PR DESCRIPTION
**Pull request by flipchart**
The `.indexOf` pattern was wrong: the colon was outside the quotes

### CODE REVIEW

**Comment by grabbou** [comment]
Hey!

What about the second check that does have quotes?
` ~content.indexOf(`':${name}'`

**Comment by flipchart** [comment]
Before:

    (content) => ~content.indexOf(`:"${name}"`) || ~content.indexOf(`':${name}'`),
                                   ^  outside quotes

After:

    (content) => ~content.indexOf(`":${name}"`) || ~content.indexOf(`':${name}'`),
                                    ^ inside quotes

The second check is fine because the colon is inside the (single) quotes. The first check is looking for double quotes.

**Comment by grabbou** [comment]
Ah, true, entirely missed that!

@Kureev do we need quotes in the second check? Can't it simply be `:${name}` ?

**Comment by Kureev** [comment]
Actually, we always need to check for this pattern:
https://github.com/rnpm/rnpm-plugin-link/blob/master/src/android/patches/makeBuildPatch.js#L9

**Comment by Kureev** [comment]
Simply put, we need to check for `:${name}`

**Comment by grabbou** [comment]
Anyone wants to make a PR?

**Comment by Kureev** [comment]
I'm planning to round off my side activities before the weekend and resume working on rnpm. 
That would be a first thingy I'll tackle if nobody submit a PR before.

**Comment by grabbou** [comment]
Closing in favour of #49 that slightly unifies these checks since `"` and `'` are irrelevant! Thanks for bringing this up to the table - it's been a valuable hint! I hope the fact we are merging another PR does not discourage you from further contributing to this project! The more Android heros here the better for all of us!

**Pull request closed without merging**
