### PR TITLE
Extract few lodash methods and simplify unit tests

### PR DESCRIPTION
**Pull request by grabbou**

### CODE REVIEW

**Comment by grabbou** [comment]
Merge after #44 since there's going to be a conflict in link.spec.js (feel free to resolve yourself or let me know)

**Comment by Kureev** [comment]
What about `getProjectDependencies.spec`?

**Comment by Kureev** [comment]
I merged #44 first, but still a conflict.

**Comment by grabbou** [comment]
Ok, doing that now

**Comment by grabbou** [comment]
@Kureev done

**Comment by Kureev** [comment]
Errm, sorry, but seems we have to do it once again because of #41

**Comment by grabbou** [comment]
@Kureev TODO: Replace `union`

**Comment by grabbou** [comment]
Commits to be squashed :)

**Comment by Kureev** [comment]
Clean it up and I'll review it :wink:

**Comment by grabbou** [comment]
It's cleaned up already, it's just these commit messages that are temporary, but it should not affect the review.

**Comment by Kureev** [comment]
I just though you want to squash them :)

**Comment by Kureev** [comment]
otherwise, just merge it in, I'm fine with the changes

**Comment by grabbou** [comment]
Ah okey - just let me know if it looks good to you and I'll squash & merge later for you to save you time!

**Comment by Kureev** [comment]
LGTM :+1:

**Pull request merged**
