### PR TITLE
Follow up to #46

### PR DESCRIPTION
**Pull request by grabbou**
Just submitting a PR - I think that change should not hurt anyone. Maybe we could use regex to find a `: ("|') ${name} ("|')` (stuff in brackets is optional)

### CODE REVIEW

**Comment by Kureev** [comment]
We can, but we don't need to. Our code always links it using one pattern: `:react-native-plugin-name` (without " or ') if you want a more generic pattern, then remove `:` in general. If you have a plugin name in the file, it's installed.

**Comment by Kureev** [comment]
I wanna say that `:"something"` is never a correct pattern.

**Comment by grabbou** [comment]
Ah, cool. You are right with the double quote - haven't checked the gradle when suggesting that :D

**Comment by Kureev** [comment]
Then seems I'm doing it wrong now :smiley:

**Comment by grabbou** [comment]
Yeah I just checked and it's:
```
    compile project(":react-native-fs")
    compile project(":react-native-google-analytics-bridge")
    compile project(":react-native-linear-gradient")
    compile project(":RNMail")
```
in one of my projects.

**Pull request merged**
